version: "3.8"
services:
  api:
    build: ./api
    container_name: ndi_c
    ports:
      - '4000:4000'
    volumes:
      - ./api:/ndi
      - ./api:/ndi/node_modules
  myblog:
    build: ./myblog
    container_name: myblog_c
    ports:
      - '3000:3000'
    stdin_open: true
